language: node_js
node_js:
  - "node"
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
script:
  - hugo
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure:"1//06jX1y0vMv-QiCgYIARAAGAYSNwF-L9Ir6Mxn9XRZ9Cmh-AWrW3NUjVMahi-MqRWjk4iNnFUIZsCRZSezSRuNZhFm0PCglH7jWMc"
