baseURL = "https://wendyhackermom.com"
languageCode = "en-us"
title = "Wendy's Hacker Mom Space"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
disqusShortname = "hackermom"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Lazy geeky parents who just want to minimize work and maximize parenting outcome"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[Author]
  name = "Wendy K"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "wendykan"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
  instagram = "chefbenko.jr"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
